# Generated by Django 3.2.15 on 2022-08-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_owner',
            name='age',
            field=models.IntegerField(default=26),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_car', to='relations.car_owner'),
        ),
    ]
